### ISSUE TITLE
OTF Fonts missing?

### ISSUE THREAD

**Issue by zabarabab** [flathub/net.scribus.Scribus#21]
I installed Scribus using Flatpak. When I open a file I got, Scribus wants to replace some FiraCode Fonts. 
But I have them installed in /usr/share/fonts/opentype/firacode
Maybe Scribus does not have access to it?

Version: 1.5.6.svn

**Comment by jurf** [comment]
Scribus should have access to all your fonts via Flatpak. Try if other Flatpak apps see the font.

**Comment by riveravaldez** [comment]
Hi, the problem seems to be flatpak-general (not Scribus-exclusive, let's say).
I have just found this issue with the last version of Scribus and **also** with the last version of AbiWord (also from _flathub_):

```
$ flatpak info com.abisource.AbiWord

AbiWord - A word processor

          ID: com.abisource.AbiWord
  Referencia: app/com.abisource.AbiWord/x86_64/stable
Arquitectura: x86_64
        Rama: stable
     Version: 3.0.4
     License: GPL-2.0-or-later
      Origen: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 49,9 MB
     Runtime: org.gnome.Platform/x86_64/3.38
         Sdk: org.gnome.Sdk/x86_64/3.38

      Commit: 2636c525519b8069674f286a4ed750c2fe1ce3b3c1abb7565c43d46d3c409515
      Parent: 05c536c07d1e818735cab7589484668d1d774eb5bcc5f5082ae7783f83fd24db
     Subject: Use GNOME 3.38 runtime (3b8c42d4)
        Date: 2020-09-19 03:57:40 +0000
```

Created an AbiWord file with the AbiWord version from Debian (testing, updated) repositories (`3.0.4~dfsg-2`), typed some text, and applied to it some font I have installed. Opening the file with that version of AbiWord shows the text with that font correctly.
Instead, if I open the file with flatpak's AbiWord then the font doesn't seems to load and gets replaced with some other (but the name of the font in the toolbar is the right one).

Hope this help. Let me know if I can do something else.

Thanks a lot!

**Comment by jurf** [comment]
Please file this over at https://github.com/flatpak/flatpak; there’s not much I can help you with here.
